from datetime import date, datetime, timezone

from sqlalchemy import Date, DateTime, Float, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class PriceHistory(Base):
    """One estimated price for a specific route+class+stops+airline on a
    given travel date.

    Stored at full (airline, stops) granularity rather than collapsed to
    "cheapest only" — this is what lets the API filter by airline/stops
    and still answer "what's the cheapest across everything" by taking
    MIN(price) per date over whichever subset matches the filters.

    `source` distinguishes how the row was produced:
      - "model_estimate": generated by running the real trained XGBoost model
        across a date range (today's placeholder for a live price feed).
      - "synthetic_shock": a deliberately injected anomaly for demoing the
        anomaly-detection algorithm against, clearly labeled as such.
      - "amadeus": reserved for when the real Amadeus polling job lands.
    """

    __tablename__ = "price_history"
    __table_args__ = (
        UniqueConstraint(
            "source_city", "destination_city", "flight_class", "travel_date", "stops", "airline",
            name="uq_price_history_route_class_date_stops_airline",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    source_city: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    destination_city: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    flight_class: Mapped[str] = mapped_column(String(20), nullable=False)
    travel_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    stops: Mapped[str] = mapped_column(String(20), nullable=False, default="zero")
    airline: Mapped[str] = mapped_column(String(30), nullable=False, default="Vistara")
    duration: Mapped[float] = mapped_column(Float, nullable=False, default=2.5)
    price: Mapped[float] = mapped_column(Float, nullable=False)
    source: Mapped[str] = mapped_column(String(30), default="model_estimate", nullable=False)
    collected_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )
