import React, { useState } from 'react';
import { IndianRupee, Clock, MapPin, Plane, TrendingUp, Sparkles, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';
import { predictPrice, getModelInfo, FLIGHT_OPTIONS } from '../api/client';

// Human-readable label for a SHAP feature key, using the actual values the
// user searched with — "class" -> "Economy Class", "duration" -> "Duration 2.5 h".
const shapFeatureLabel = (featureKey, formData) => {
    switch (featureKey) {
        case 'class':
            return `${formData.class} Class`;
        case 'days_left':
            return `${formData.days_left} Days Left`;
        case 'duration':
            return `Duration ${formData.duration} h`;
        case 'airline':
            return formData.airline.replace('_', ' ');
        case 'source_city':
            return `From ${formData.source_city}`;
        case 'destination_city':
            return `To ${formData.destination_city}`;
        case 'stops':
            return FLIGHT_OPTIONS.stops.find((s) => s.value === formData.stops)?.label || formData.stops;
        case 'departure_time':
            return `Departs ${formData.departure_time.replace('_', ' ')}`;
        case 'arrival_time':
            return `Arrives ${formData.arrival_time.replace('_', ' ')}`;
        default:
            return featureKey;
    }
};

const formatSigned = (value) => `${value >= 0 ? '+' : '-'}₹${Math.abs(value).toLocaleString('en-IN')}`;

const PricePrediction = ({ initialValues }) => {
    const [formData, setFormData] = useState({
        airline: 'Vistara',
        source_city: 'Delhi',
        destination_city: 'Mumbai',
        departure_time: 'Morning',
        arrival_time: 'Afternoon',
        stops: 'one',
        class: 'Economy',
        duration: 2.5,
        days_left: 10,
        ...initialValues,
    });

    const [prediction, setPrediction] = useState(null);
    const [modelInfo, setModelInfo] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData((prev) => ({
            ...prev,
            [name]: name === 'duration' || name === 'days_left' ? Number(value) : value,
        }));
    };

    const handlePredict = async (e) => {
        e.preventDefault();

        if (formData.source_city === formData.destination_city) {
            toast.error('Source and destination cities must be different');
            return;
        }

        setLoading(true);
        setError(null);

        try {
            const [predictionResult, info] = await Promise.all([
                predictPrice(formData),
                getModelInfo(),
            ]);
            setPrediction(predictionResult);
            setModelInfo(info);
            toast.success('Price prediction generated by the live model');
        } catch (err) {
            const message =
                err.response?.data?.detail?.[0]?.msg ||
                err.response?.data?.detail ||
                'Could not reach the prediction API. Is the backend running on :8000?';
            setError(typeof message === 'string' ? message : 'Prediction request failed');
            toast.error('Prediction failed');
        } finally {
            setLoading(false);
        }
    };

    const topFeatures = modelInfo
        ? Object.entries(modelInfo.feature_importance).slice(0, 5)
        : [];

    const glassCard = 'rounded-2xl border border-white/15 bg-white/5 shadow-lg p-6 transition-all duration-300';
    const cardHeader = 'flex justify-between items-center mb-6 pb-4 border-b border-white/10';
    const cardTitle = 'flex items-center gap-2 text-xl font-semibold text-white';
    const glassLabel = 'flex items-center gap-1 text-sm font-semibold text-white/70';
    const glassInput = 'w-full px-4 py-2 rounded-md text-sm transition-all duration-300 bg-white/5 border border-white/15 text-white focus:outline-none focus:border-cyan-300/60 focus:ring-3 focus:ring-cyan-300/15';

    return (
        <div className="flex flex-col gap-8">
            <div className="flex justify-between items-start mb-2 flex-col lg:flex-row gap-4">
                <div>
                    <h1 className="text-3xl font-extrabold text-white mb-1">Price Prediction</h1>
                    <p className="text-base text-white/60">
                        Real XGBoost model trained on 300K+ Indian domestic flight fares
                    </p>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
                <div className={`${glassCard} static lg:sticky lg:top-[calc(80px+2rem)]`}>
                    <div className={cardHeader}>
                        <h3 className={cardTitle}>Flight Details</h3>
                        <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-semibold uppercase tracking-wider bg-cyan-400/15 text-cyan-300 border border-cyan-300/40">
                            <Sparkles size={12} />
                            ML Powered
                        </span>
                    </div>

                    <form onSubmit={handlePredict} className="flex flex-col gap-6">
                        <div className="form-row">
                            <div className="form-group">
                                <label className={glassLabel}>
                                    <MapPin size={16} />
                                    Source City
                                </label>
                                <select
                                    name="source_city"
                                    value={formData.source_city}
                                    onChange={handleInputChange}
                                    className={`${glassInput} cursor-pointer`}
                                >
                                    {FLIGHT_OPTIONS.cities.map((c) => (
                                        <option key={c.value} value={c.value}>{c.label}</option>
                                    ))}
                                </select>
                            </div>

                            <div className="form-group">
                                <label className={glassLabel}>
                                    <MapPin size={16} />
                                    Destination City
                                </label>
                                <select
                                    name="destination_city"
                                    value={formData.destination_city}
                                    onChange={handleInputChange}
                                    className={`${glassInput} cursor-pointer`}
                                >
                                    {FLIGHT_OPTIONS.cities.map((c) => (
                                        <option key={c.value} value={c.value}>{c.label}</option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        <div className="form-row">
                            <div className="form-group">
                                <label className={glassLabel}>
                                    <Clock size={16} />
                                    Departure Time
                                </label>
                                <select
                                    name="departure_time"
                                    value={formData.departure_time}
                                    onChange={handleInputChange}
                                    className={`${glassInput} cursor-pointer`}
                                >
                                    {FLIGHT_OPTIONS.timesOfDay.map((t) => (
                                        <option key={t.value} value={t.value}>{t.label}</option>
                                    ))}
                                </select>
                            </div>

                            <div className="form-group">
                                <label className={glassLabel}>
                                    <Clock size={16} />
                                    Arrival Time
                                </label>
                                <select
                                    name="arrival_time"
                                    value={formData.arrival_time}
                                    onChange={handleInputChange}
                                    className={`${glassInput} cursor-pointer`}
                                >
                                    {FLIGHT_OPTIONS.timesOfDay.map((t) => (
                                        <option key={t.value} value={t.value}>{t.label}</option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        <div className="form-row">
                            <div className="form-group">
                                <label className={glassLabel}>
                                    <Plane size={16} />
                                    Stops
                                </label>
                                <select
                                    name="stops"
                                    value={formData.stops}
                                    onChange={handleInputChange}
                                    className={`${glassInput} cursor-pointer`}
                                >
                                    {FLIGHT_OPTIONS.stops.map((s) => (
                                        <option key={s.value} value={s.value}>{s.label}</option>
                                    ))}
                                </select>
                            </div>

                            <div className="form-group">
                                <label className={glassLabel}>
                                    <Sparkles size={16} />
                                    Class
                                </label>
                                <select
                                    name="class"
                                    value={formData.class}
                                    onChange={handleInputChange}
                                    className={`${glassInput} cursor-pointer`}
                                >
                                    {FLIGHT_OPTIONS.classes.map((c) => (
                                        <option key={c.value} value={c.value}>{c.label}</option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        <div className="form-row">
                            <div className="form-group">
                                <label className={glassLabel}>
                                    <Clock size={16} />
                                    Duration (hours)
                                </label>
                                <input
                                    type="number"
                                    name="duration"
                                    min="0.5"
                                    max="49.9"
                                    step="0.1"
                                    value={formData.duration}
                                    onChange={handleInputChange}
                                    className={glassInput}
                                    required
                                />
                            </div>

                            <div className="form-group">
                                <label className={glassLabel}>
                                    <Clock size={16} />
                                    Days Until Departure
                                </label>
                                <input
                                    type="number"
                                    name="days_left"
                                    min="1"
                                    max="49"
                                    value={formData.days_left}
                                    onChange={handleInputChange}
                                    className={glassInput}
                                    required
                                />
                            </div>
                        </div>

                        <div className="form-group">
                            <label className={glassLabel}>
                                <Plane size={16} />
                                Airline
                            </label>
                            <select
                                name="airline"
                                value={formData.airline}
                                onChange={handleInputChange}
                                className={`${glassInput} cursor-pointer`}
                            >
                                {FLIGHT_OPTIONS.airlines.map((a) => (
                                    <option key={a.value} value={a.value}>{a.label}</option>
                                ))}
                            </select>
                        </div>

                        <button
                            type="submit"
                            className="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-md text-base font-semibold cursor-pointer transition-all duration-300 border-none bg-linear-to-br from-cyan-400 to-blue-600 text-white shadow-lg hover:shadow-[0_0_20px_rgba(103,232,249,0.4)] hover:-translate-y-0.5 disabled:opacity-60 disabled:cursor-not-allowed disabled:hover:translate-y-0"
                            disabled={loading}
                        >
                            {loading ? (
                                <>
                                    <div className="animate-spin">⏳</div>
                                    Predicting...
                                </>
                            ) : (
                                <>
                                    <TrendingUp size={20} />
                                    Predict Price
                                </>
                            )}
                        </button>

                        {error && (
                            <p className="text-[#ef4444] mt-2">
                                {error}
                            </p>
                        )}
                    </form>
                </div>

                <div className="flex flex-col gap-6">
                    {prediction ? (
                        <>
                            <div className="rounded-2xl border border-cyan-300/30 bg-linear-to-br from-cyan-500/25 to-blue-700/25 shadow-lg p-6 text-white">
                                <div className="flex items-center gap-6 mb-6">
                                    <IndianRupee size={32} className="p-4 bg-white/15 border border-white/20 rounded-xl" />
                                    <div>
                                        <p className="text-sm opacity-90 mb-1">Predicted Price</p>
                                        <h2 className="text-4xl font-extrabold leading-none">
                                            ₹{prediction.predicted_price.toLocaleString('en-IN')}
                                        </h2>
                                        <p className="text-sm opacity-80 mt-1">
                                            Model {prediction.model_version}
                                            {prediction.out_of_distribution && (
                                                <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-semibold uppercase tracking-wider bg-orange-400/15 text-orange-300 border border-orange-300/40" style={{ marginLeft: '8px' }}>
                                                    <AlertTriangle size={12} /> Low confidence — unusual inputs
                                                </span>
                                            )}
                                        </p>
                                    </div>
                                </div>

                                <div className="flex items-center gap-4 p-4 bg-white/10 rounded-md">
                                    <div className="flex flex-col items-center gap-1">
                                        <span className="text-xs opacity-80">Low</span>
                                        <span className="text-lg font-bold">
                                            ₹{prediction.confidence_low.toLocaleString('en-IN')}
                                        </span>
                                    </div>
                                    <div className="flex-1 h-2 bg-white/20 rounded-full relative overflow-hidden">
                                        <div className="absolute left-1/2 -translate-x-1/2 w-3 h-3 bg-white rounded-full -top-0.5 shadow-[0_0_10px_rgba(255,255,255,0.5)]"></div>
                                    </div>
                                    <div className="flex flex-col items-center gap-1">
                                        <span className="text-xs opacity-80">High</span>
                                        <span className="text-lg font-bold">
                                            ₹{prediction.confidence_high.toLocaleString('en-IN')}
                                        </span>
                                    </div>
                                </div>
                            </div>

                            {prediction.shap_contributions && (
                                <div className={glassCard}>
                                    <div className={cardHeader}>
                                        <h3 className={cardTitle}>Why This Price (SHAP, this prediction only)</h3>
                                    </div>
                                    <pre className="m-0 p-6 bg-white/5 border border-white/10 rounded-md font-mono text-[13px] whitespace-pre-wrap overflow-x-auto text-white/70">
                                        <div className="flex justify-between gap-4 py-1">
                                            <span className="text-white font-semibold">Base (Average) Price</span>
                                            <span className="text-white font-semibold">₹{prediction.base_value.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</span>
                                        </div>
                                        <div className="border-t border-dashed border-white/15 my-1.5" />
                                        {prediction.shap_contributions.map((c) => (
                                            <div key={c.feature} className="flex justify-between gap-4 py-1">
                                                <span>{shapFeatureLabel(c.feature, formData)}</span>
                                                <span className={c.impact >= 0 ? 'text-red-400' : 'text-emerald-400'}>
                                                    {formatSigned(c.impact)}
                                                </span>
                                            </div>
                                        ))}
                                        {prediction.other_features_impact !== 0 && (
                                            <div className="flex justify-between gap-4 py-1 italic text-white/50">
                                                <span>Other Features</span>
                                                <span className={prediction.other_features_impact >= 0 ? 'text-red-400' : 'text-emerald-400'}>
                                                    {formatSigned(prediction.other_features_impact)}
                                                </span>
                                            </div>
                                        )}
                                        <div className="border-t border-dashed border-white/15 my-1.5" />
                                        <div className="flex justify-between gap-4 py-1 font-bold text-sm">
                                            <span className="text-white">Final Prediction</span>
                                            <span className="text-white">₹{prediction.predicted_price.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</span>
                                        </div>
                                    </pre>
                                </div>
                            )}

                            {modelInfo && (
                                <div className={glassCard}>
                                    <div className={cardHeader}>
                                        <h3 className={cardTitle}>Top Price Drivers Overall (training-time feature importance)</h3>
                                    </div>
                                    <div className="flex flex-col gap-4">
                                        {topFeatures.map(([name, score]) => (
                                            <div key={name} className="flex justify-between items-center p-4 bg-white/5 rounded-md transition-all duration-300 hover:bg-white/10 hover:translate-x-1">
                                                <div className="flex items-center gap-4">
                                                    <span className="text-sm text-white font-medium">{name}</span>
                                                </div>
                                                <span className="text-base font-bold text-cyan-300">{(score * 100).toFixed(1)}%</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {modelInfo && (
                                <div className={glassCard}>
                                    <div className={cardHeader}>
                                        <h3 className={cardTitle}>Model Accuracy (held-out test set)</h3>
                                    </div>
                                    <ul className="list-none flex flex-col gap-4">
                                        <li className="flex items-start gap-2 p-4 bg-white/5 border-l-[3px] border-l-cyan-400 rounded-md text-sm text-white/70 transition-all duration-300 hover:bg-white/10 hover:translate-x-1">
                                            <Sparkles size={16} className="flex-shrink-0 text-cyan-300 mt-0.5" />
                                            MAE: ₹{modelInfo.metrics.mae.toFixed(0)} | R²: {modelInfo.metrics.r2.toFixed(3)}
                                        </li>
                                        <li className="flex items-start gap-2 p-4 bg-white/5 border-l-[3px] border-l-cyan-400 rounded-md text-sm text-white/70 transition-all duration-300 hover:bg-white/10 hover:translate-x-1">
                                            <Sparkles size={16} className="flex-shrink-0 text-cyan-300 mt-0.5" />
                                            Trained on {modelInfo.dataset}
                                        </li>
                                    </ul>
                                </div>
                            )}
                        </>
                    ) : (
                        <div className={`${glassCard} flex items-center justify-center text-center`} style={{ minHeight: 320 }}>
                            <div className="flex flex-col items-center gap-3">
                                <IndianRupee size={64} className="text-white/25" />
                                <h3 className="text-xl font-semibold text-white">No Prediction Yet</h3>
                                <p className="text-base text-white/55 max-w-80">
                                    Fill in the flight details and click "Predict Price" to query the live model
                                </p>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default PricePrediction;
