"""add flight_class to watchlists, create alerts table

Revision ID: 9450e1f11c43
Revises: b3859fcdbe4c
Create Date: 2026-06-25 20:55:01.866651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9450e1f11c43'
down_revision: Union[str, Sequence[str], None] = 'b3859fcdbe4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('price_at_trigger', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'travel_date', name='uq_alert_watchlist_date')
    )
    op.add_column(
        'watchlists',
        sa.Column('flight_class', sa.String(length=20), nullable=False, server_default='Economy'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlists', 'flight_class')
    op.drop_table('alerts')
    # ### end Alembic commands ###
