"""expand price_history with airline, stops, duration

Revision ID: a84dc779131e
Revises: c8df5b33dd3f
Create Date: 2026-06-26 19:34:56.514878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84dc779131e'
down_revision: Union[str, Sequence[str], None] = 'c8df5b33dd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # price_history is fully regenerable derived data (re-created by
    # app/jobs/generate_price_history.py) — clear it rather than backfill
    # fake values for the new NOT NULL columns.
    op.execute("DELETE FROM price_history")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('stops', sa.String(length=20), nullable=False))
    op.add_column('price_history', sa.Column('airline', sa.String(length=30), nullable=False))
    op.add_column('price_history', sa.Column('duration', sa.Float(), nullable=False))
    op.drop_constraint(op.f('uq_price_history_route_class_date'), 'price_history', type_='unique')
    op.create_unique_constraint('uq_price_history_route_class_date_stops_airline', 'price_history', ['source_city', 'destination_city', 'flight_class', 'travel_date', 'stops', 'airline'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_price_history_route_class_date_stops_airline', 'price_history', type_='unique')
    op.create_unique_constraint(op.f('uq_price_history_route_class_date'), 'price_history', ['source_city', 'destination_city', 'flight_class', 'travel_date'], postgresql_nulls_not_distinct=False)
    op.drop_column('price_history', 'duration')
    op.drop_column('price_history', 'airline')
    op.drop_column('price_history', 'stops')
    # ### end Alembic commands ###
