"""create price_history

Revision ID: b3859fcdbe4c
Revises: 65c4edf4ebfd
Create Date: 2026-06-25 20:26:02.144492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3859fcdbe4c'
down_revision: Union[str, Sequence[str], None] = '65c4edf4ebfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_city', sa.String(length=50), nullable=False),
    sa.Column('destination_city', sa.String(length=50), nullable=False),
    sa.Column('flight_class', sa.String(length=20), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_city', 'destination_city', 'flight_class', 'travel_date', name='uq_price_history_route_class_date')
    )
    op.create_index(op.f('ix_price_history_destination_city'), 'price_history', ['destination_city'], unique=False)
    op.create_index(op.f('ix_price_history_source_city'), 'price_history', ['source_city'], unique=False)
    op.create_index(op.f('ix_price_history_travel_date'), 'price_history', ['travel_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_travel_date'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_source_city'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_destination_city'), table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###
