"""add is_verified to users

Revision ID: c8df5b33dd3f
Revises: 9450e1f11c43
Create Date: 2026-06-26 03:26:30.180159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8df5b33dd3f'
down_revision: Union[str, Sequence[str], None] = '9450e1f11c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Grandfather existing users as verified — this feature is new, and
    # retroactively locking out accounts created before it existed would
    # be a self-inflicted outage, not a security improvement.
    op.add_column(
        'users',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
